const LABS_CONFIG = [
  { id: 'LAB_LUCI',   name: 'Luci + Proiezione',       capacity: 4, tutor: 'Zeno',                 room: 'Regia' },
  { id: 'LAB_VIDEO',  name: 'Video',                   capacity: 4, tutor: 'Lorenzo',               room: 'Sala Traduzione' },
  { id: 'LAB_AUDIO',  name: 'Audio',                   capacity: 5, tutor: 'Kevin + Zucchiatti',    room: 'Fondo platea' },
  { id: 'LAB_DRONI',  name: 'Coreografia con i Droni', capacity: 8, tutor: 'Fabio + Andreas',       room: 'Sala Don Bosco' },
  { id: 'LAB_PRES',   name: 'Presentatori',            capacity: 2, tutor: 'Don Daniele',           room: 'Ufficio Presidente' },
  { id: 'LAB_NAO',    name: 'Balletto con NAO',         capacity: 3, tutor: 'Luca Zani + Maya',     room: 'Primo piano Juvenes' },
  { id: 'LAB_COMEDY', name: 'Sketch Comico',           capacity: 5, tutor: 'Fabrizio + Frederiko',  room: 'Sala Giochi' },
];

// SCORING BIPOLARE: il punteggio è (sliderValue - 5) × impatto, dove sliderValue ∈ [0,10].
//   - slider tutto a destra (10) → factor +5  → premia i lab con impatto POSITIVO
//   - slider tutto a sinistra (0) → factor -5 → premia i lab con impatto NEGATIVO
//   - slider al centro (5)        → factor  0 → nessun effetto (nessuna preferenza)
// REGOLA SEGNI: i lab affini all'opzione DESTRA (labelRight) = impatto POSITIVO;
//               i lab affini all'opzione SINISTRA (labelLeft) = impatto NEGATIVO.
const QUESTIONS = [
  {
    id: 'Q01',
    testo: 'Hai mai recitato in un film, o ti piacerebbe farlo?',
    labelLeft: 'No, per nulla',
    labelRight: 'Sì, mi piacerebbe molto',
    impatto: { LAB_COMEDY: 3, LAB_VIDEO: 1 },
  },
  {
    id: 'Q02',
    testo: 'Ti piace essere al centro dell\'attenzione davanti a tutti?',
    labelLeft: 'Per nulla',
    labelRight: 'Moltissimo',
    impatto: { LAB_PRES: 4, LAB_COMEDY: 4, LAB_LUCI: -2, LAB_AUDIO: -2 },
  },
  {
    id: 'Q03',
    testo: 'Se vedi un robot o un drone, preferisci guardarlo o programmare i suoi movimenti?',
    labelLeft: 'Solo guardarlo',
    labelRight: 'Programmare i movimenti',
    impatto: { LAB_DRONI: 4, LAB_NAO: 4, LAB_COMEDY: -3 },
  },
  {
    id: 'Q04',
    testo: 'Nello strutturare una performance sul palco, cosa preferiresti fare?',
    labelLeft: 'Far ridere di gusto',
    labelRight: 'Coordinare e presentare',
    impatto: { LAB_COMEDY: -5, LAB_PRES: 5 },
  },
  {
    id: 'Q05',
    testo: 'Ti affascina di più controllare le luci di uno spettacolo o mixare il suono?',
    labelLeft: 'Controllare le luci',
    labelRight: 'Mixare il suono',
    impatto: { LAB_LUCI: -3, LAB_AUDIO: 3 },
  },
  {
    id: 'Q06',
    testo: 'Quanto ti appassionano la danza e le coreografie?',
    labelLeft: 'Non è per me',
    labelRight: 'È la mia passione',
    impatto: { LAB_NAO: 4, LAB_DRONI: 2, LAB_COMEDY: 1 },
  },
  {
    id: 'Q07',
    testo: 'Quanto ti piace girare e montare video?',
    labelLeft: 'Per nulla',
    labelRight: 'Moltissimo',
    impatto: { LAB_VIDEO: 5, LAB_DRONI: 1, LAB_NAO: 1 },
  },
  {
    id: 'Q08',
    testo: 'Ti piacerebbe condurre un evento come un presentatore professionista?',
    labelLeft: 'No, non è il mio stile',
    labelRight: 'Sì, sarebbe fantastico',
    impatto: { LAB_PRES: 5, LAB_COMEDY: 2, LAB_VIDEO: 1, LAB_LUCI: -2, LAB_AUDIO: -2 },
  },
  {
    id: 'Q09',
    testo: 'Quanto ti affascina il mondo dell\'audio professionale e dei microfoni?',
    labelLeft: 'Per niente',
    labelRight: 'Molto',
    impatto: { LAB_AUDIO: 5, LAB_VIDEO: 2, LAB_LUCI: 1, LAB_COMEDY: -2 },
  },
  {
    id: 'Q10',
    testo: 'Durante uno spettacolo, preferisci stare dietro le quinte o brillare sul palco?',
    labelLeft: 'Dietro le quinte',
    labelRight: 'Sul palco',
    impatto: { LAB_LUCI: -3, LAB_AUDIO: -3, LAB_VIDEO: -2, LAB_PRES: 4, LAB_COMEDY: 3, LAB_NAO: 2 },
  },
  {
    id: 'Q11',
    testo: 'Ti entusiasma l\'idea di programmare un robot umanoide che balla?',
    labelLeft: 'Non particolarmente',
    labelRight: 'Assolutamente sì!',
    impatto: { LAB_NAO: 5, LAB_DRONI: 3, LAB_COMEDY: -2, LAB_PRES: -2 },
  },
  {
    id: 'Q12',
    testo: 'Quanto ti piace improvvisare e far ridere le persone?',
    labelLeft: 'Non è il mio forte',
    labelRight: 'Lo adoro!',
    impatto: { LAB_COMEDY: 5, LAB_LUCI: -2, LAB_AUDIO: -2, LAB_VIDEO: -1 },
  },
  {
    id: 'Q13',
    testo: 'L\'idea di coordinare una danza aerea con i droni ti sembra...',
    labelLeft: 'Non mi interessa',
    labelRight: 'Incredibilmente figo!',
    impatto: { LAB_DRONI: 5, LAB_NAO: 2, LAB_VIDEO: 1, LAB_COMEDY: -2 },
  },
  {
    id: 'Q14',
    testo: 'Se hai un tablet con un software di programmazione avanzato, cosa fai?',
    labelLeft: 'Lo lascio ad altri',
    labelRight: 'Ci gioco subito',
    impatto: { LAB_DRONI: 4, LAB_NAO: 4, LAB_LUCI: 2, LAB_AUDIO: 2, LAB_VIDEO: 2, LAB_PRES: -3, LAB_COMEDY: -3 },
  },
  {
    id: 'Q15',
    testo: 'Preferisci lavorare in cabina di regia o stare davanti al pubblico?',
    labelLeft: 'In cabina, a controllare tutto',
    labelRight: 'Davanti al pubblico',
    impatto: { LAB_LUCI: -4, LAB_AUDIO: -4, LAB_VIDEO: -3, LAB_PRES: 5, LAB_COMEDY: 4, LAB_NAO: 2, LAB_DRONI: -1 },
  },
  {
    id: 'Q16',
    testo: 'Quanto ti piace giocare con i colori, le ombre e gli effetti visivi di uno spettacolo?',
    labelLeft: 'Non ci penso mai',
    labelRight: 'Mi affascina tantissimo',
    impatto: { LAB_LUCI: 5, LAB_VIDEO: 2, LAB_DRONI: 1, LAB_AUDIO: -2 },
  },
  {
    id: 'Q17',
    testo: 'Saper raccontare una storia con le immagini in movimento è una cosa che...',
    labelLeft: 'Non mi interessa',
    labelRight: 'Vorrei imparare assolutamente',
    impatto: { LAB_VIDEO: 5, LAB_LUCI: 2, LAB_DRONI: 1, LAB_AUDIO: -1 },
  },
  {
    id: 'Q18',
    testo: 'Se senti una canzone, ti concentri di più sul ritmo e sul suono o su come ballarla?',
    labelLeft: 'Sul suono e sul ritmo',
    labelRight: 'Su come ballarla',
    impatto: { LAB_AUDIO: -4, LAB_NAO: 4, LAB_DRONI: 1 },
  },
  {
    id: 'Q19',
    testo: 'Quanto ti senti a tuo agio a parlare a un microfono davanti a una sala piena?',
    labelLeft: 'Mi mette ansia',
    labelRight: 'Mi diverte un sacco',
    impatto: { LAB_PRES: 5, LAB_COMEDY: 3, LAB_LUCI: -2, LAB_AUDIO: -1 },
  },
  {
    id: 'Q20',
    testo: 'Preferisci risolvere un problema tecnico complicato o intrattenere un gruppo di amici?',
    labelLeft: 'Risolvere il problema tecnico',
    labelRight: 'Intrattenere gli amici',
    impatto: { LAB_DRONI: -4, LAB_NAO: -3, LAB_LUCI: -2, LAB_COMEDY: 4, LAB_PRES: 3 },
  },
  {
    id: 'Q21',
    testo: 'Ti piace l\'idea di far volare qualcosa nel cielo e disegnare figure con esso?',
    labelLeft: 'Non particolarmente',
    labelRight: 'Sarebbe spettacolare',
    impatto: { LAB_DRONI: 5, LAB_NAO: 2, LAB_LUCI: 1, LAB_PRES: -2 },
  },
  {
    id: 'Q22',
    testo: 'Quando guardi uno spettacolo, noti di più la musica o la scenografia luminosa?',
    labelLeft: 'La musica e i suoni',
    labelRight: 'Le luci e la scenografia',
    impatto: { LAB_AUDIO: -4, LAB_LUCI: 4, LAB_VIDEO: 1 },
  },
  {
    id: 'Q23',
    testo: 'Ti diverte di più fare battute spiritose o ballare a tempo di musica?',
    labelLeft: 'Fare battute spiritose',
    labelRight: 'Ballare a tempo',
    impatto: { LAB_COMEDY: -5, LAB_NAO: 5, LAB_PRES: -1 },
  },
  {
    id: 'Q24',
    testo: 'Quanto ti piacerebbe imparare a usare attrezzature professionali come telecamere e mixer?',
    labelLeft: 'Per niente',
    labelRight: 'Tantissimo',
    impatto: { LAB_VIDEO: 4, LAB_AUDIO: 4, LAB_LUCI: 3, LAB_COMEDY: -2, LAB_PRES: -2 },
  },
  {
    id: 'Q25',
    testo: 'Preferisci un ruolo dove sei tu protagonista o uno dove rendi protagonisti gli altri?',
    labelLeft: 'Rendere protagonisti gli altri',
    labelRight: 'Essere il protagonista',
    impatto: { LAB_LUCI: -4, LAB_AUDIO: -4, LAB_VIDEO: -3, LAB_PRES: 5, LAB_COMEDY: 4, LAB_NAO: 1 },
  },
  {
    id: 'Q26',
    testo: 'L\'idea di sincronizzare luci, suoni ed effetti a tempo perfetto ti...',
    labelLeft: 'Lascia indifferente',
    labelRight: 'Entusiasma molto',
    impatto: { LAB_LUCI: 4, LAB_AUDIO: 4, LAB_VIDEO: 2, LAB_DRONI: 2, LAB_COMEDY: -2 },
  },
  {
    id: 'Q27',
    testo: 'Quanto sei attratto dalla tecnologia e dal capire come funzionano le macchine?',
    labelLeft: 'Poco',
    labelRight: 'Moltissimo',
    impatto: { LAB_DRONI: 5, LAB_NAO: 4, LAB_LUCI: 2, LAB_AUDIO: 2, LAB_VIDEO: 1, LAB_COMEDY: -3 },
  },
  {
    id: 'Q28',
    testo: 'Ti piacerebbe di più gestire l\'audio di tutto lo show o dare voce a un personaggio?',
    labelLeft: 'Gestire l\'audio dello show',
    labelRight: 'Dare voce a un personaggio',
    impatto: { LAB_AUDIO: -4, LAB_LUCI: -1, LAB_COMEDY: 4, LAB_PRES: 3 },
  },
  {
    id: 'Q29',
    testo: 'Quando lavori in gruppo, preferisci curare i dettagli tecnici o coordinare i movimenti?',
    labelLeft: 'Curare i dettagli tecnici',
    labelRight: 'Coordinare i movimenti',
    impatto: { LAB_LUCI: -2, LAB_AUDIO: -2, LAB_DRONI: 3, LAB_NAO: 4, LAB_PRES: 2 },
  },
  {
    id: 'Q30',
    testo: 'Riprendere un momento speciale e trasformarlo in un bel video è qualcosa che...',
    labelLeft: 'Non fa per me',
    labelRight: 'Adoro fare',
    impatto: { LAB_VIDEO: 5, LAB_LUCI: 1, LAB_DRONI: 2, LAB_AUDIO: -1 },
  },
  {
    id: 'Q31',
    testo: 'Ti senti più un tipo "creativo e artistico" o "preciso e tecnico"?',
    labelLeft: 'Preciso e tecnico',
    labelRight: 'Creativo e artistico',
    impatto: { LAB_DRONI: -2, LAB_AUDIO: -2, LAB_LUCI: -1, LAB_COMEDY: 4, LAB_NAO: 3, LAB_VIDEO: 2 },
  },
  {
    id: 'Q32',
    testo: 'Quanto ti piacerebbe far ridere una sala intera con una scenetta tutta tua?',
    labelLeft: 'Mi spaventa',
    labelRight: 'Sarebbe il mio sogno',
    impatto: { LAB_COMEDY: 5, LAB_PRES: 2, LAB_LUCI: -3, LAB_AUDIO: -3 },
  },
  {
    id: 'Q33',
    testo: 'Preferisci stare seduto a una console a controllare tutto o muoverti e usare il corpo?',
    labelLeft: 'A una console a controllare',
    labelRight: 'Muovermi e usare il corpo',
    impatto: { LAB_LUCI: -4, LAB_AUDIO: -4, LAB_NAO: 5, LAB_COMEDY: 3, LAB_DRONI: -1 },
  },
  {
    id: 'Q34',
    testo: 'L\'idea di programmare una sequenza precisa che si ripete alla perfezione ti...',
    labelLeft: 'Annoia',
    labelRight: 'Soddisfa molto',
    impatto: { LAB_DRONI: 5, LAB_NAO: 4, LAB_LUCI: 2, LAB_COMEDY: -3, LAB_PRES: -2 },
  },
  {
    id: 'Q35',
    testo: 'Ti piace di più stare in silenzio dietro le quinte o sentire gli applausi su di te?',
    labelLeft: 'In silenzio dietro le quinte',
    labelRight: 'Sentire gli applausi su di me',
    impatto: { LAB_LUCI: -4, LAB_AUDIO: -4, LAB_VIDEO: -2, LAB_PRES: 5, LAB_COMEDY: 4 },
  },
  {
    id: 'Q36',
    testo: 'Quanto ti incuriosisce il funzionamento di un robot umanoide come NAO?',
    labelLeft: 'Poco',
    labelRight: 'Tantissimo',
    impatto: { LAB_NAO: 5, LAB_DRONI: 3, LAB_LUCI: 1, LAB_COMEDY: -2 },
  },
  {
    id: 'Q37',
    testo: 'Preferisci creare l\'atmosfera giusta con le luci o catturare tutto con la telecamera?',
    labelLeft: 'Creare l\'atmosfera con le luci',
    labelRight: 'Catturare con la telecamera',
    impatto: { LAB_LUCI: -4, LAB_VIDEO: 4, LAB_AUDIO: -1 },
  },
  {
    id: 'Q38',
    testo: 'Davanti a una platea, preferiresti presentare con serietà o strappare risate?',
    labelLeft: 'Presentare con serietà',
    labelRight: 'Strappare risate',
    impatto: { LAB_PRES: -5, LAB_COMEDY: 5, LAB_LUCI: -2, LAB_AUDIO: -2 },
  },
  {
    id: 'Q39',
    testo: 'Quanto ti piace l\'idea di lavorare con droni che volano in formazione coordinata?',
    labelLeft: 'Non mi attira',
    labelRight: 'Sarebbe fantastico',
    impatto: { LAB_DRONI: 5, LAB_NAO: 2, LAB_VIDEO: 1, LAB_PRES: -2 },
  },
  {
    id: 'Q40',
    testo: 'Sei più il tipo che organizza e tiene tutto sotto controllo o che improvvisa sul momento?',
    labelLeft: 'Organizzo e controllo tutto',
    labelRight: 'Improvviso sul momento',
    impatto: { LAB_LUCI: -2, LAB_AUDIO: -2, LAB_PRES: -1, LAB_COMEDY: 5, LAB_NAO: 1 },
  },
  {
    id: 'Q41',
    testo: 'Quanto ti piacerebbe mixare musica e suoni per creare l\'effetto perfetto?',
    labelLeft: 'Per niente',
    labelRight: 'Moltissimo',
    impatto: { LAB_AUDIO: 5, LAB_LUCI: 1, LAB_VIDEO: 2, LAB_NAO: 1, LAB_PRES: -2 },
  },
  {
    id: 'Q42',
    testo: 'Quando immagini di esibirti, ti vedi più mentre balli o mentre parli al pubblico?',
    labelLeft: 'Mentre ballo',
    labelRight: 'Mentre parlo al pubblico',
    impatto: { LAB_NAO: -5, LAB_DRONI: -1, LAB_PRES: 4, LAB_COMEDY: 2 },
  },
  {
    id: 'Q43',
    testo: 'Ti senti più portato per il lavoro di squadra silenzioso o per stare sotto i riflettori?',
    labelLeft: 'Lavoro di squadra silenzioso',
    labelRight: 'Stare sotto i riflettori',
    impatto: { LAB_LUCI: -3, LAB_AUDIO: -3, LAB_VIDEO: -2, LAB_DRONI: -1, LAB_PRES: 5, LAB_COMEDY: 4 },
  },
  {
    id: 'Q44',
    testo: 'Quanto ti affascina trasformare un palco vuoto con luci colorate e proiezioni?',
    labelLeft: 'Poco',
    labelRight: 'Tantissimo',
    impatto: { LAB_LUCI: 5, LAB_VIDEO: 3, LAB_DRONI: 1, LAB_PRES: -2, LAB_COMEDY: -2 },
  },
  {
    id: 'Q45',
    testo: 'Preferisci un compito dove conta la precisione tecnica o uno dove conta l\'espressività?',
    labelLeft: 'Precisione tecnica',
    labelRight: 'Espressività e emozione',
    impatto: { LAB_DRONI: -3, LAB_AUDIO: -2, LAB_LUCI: -1, LAB_NAO: 3, LAB_COMEDY: 4, LAB_PRES: 3 },
  },
  {
    id: 'Q46',
    testo: 'Ti piacerebbe di più dirigere i movimenti di un robot o quelli del tuo corpo nella danza?',
    labelLeft: 'Dirigere i movimenti di un robot',
    labelRight: 'I movimenti del mio corpo',
    impatto: { LAB_DRONI: -4, LAB_NAO: 4, LAB_COMEDY: 1, LAB_PRES: 1 },
  },
  {
    id: 'Q47',
    testo: 'Quanto ti piace l\'idea di stare alla regia e decidere cosa vede il pubblico?',
    labelLeft: 'Non mi attira',
    labelRight: 'Mi piacerebbe molto',
    impatto: { LAB_LUCI: 4, LAB_VIDEO: 4, LAB_AUDIO: 3, LAB_PRES: -2, LAB_COMEDY: -2 },
  },
  {
    id: 'Q48',
    testo: 'Per te è più importante che lo spettacolo sia tecnicamente perfetto o emozionante e divertente?',
    labelLeft: 'Tecnicamente perfetto',
    labelRight: 'Emozionante e divertente',
    impatto: { LAB_LUCI: -2, LAB_AUDIO: -2, LAB_DRONI: -1, LAB_COMEDY: 4, LAB_PRES: 3, LAB_NAO: 2 },
  },
  {
    id: 'Q49',
    testo: 'Quanto ti piacerebbe creare una coreografia, anche per dei robot o dei droni?',
    labelLeft: 'Non è il mio campo',
    labelRight: 'Lo adorerei',
    impatto: { LAB_NAO: 4, LAB_DRONI: 4, LAB_COMEDY: 1, LAB_AUDIO: -2 },
  },
  {
    id: 'Q50',
    testo: 'Ti vedi più a curare il suono perfetto o a far divertire la gente con la tua presenza?',
    labelLeft: 'Curare il suono perfetto',
    labelRight: 'Far divertire con la presenza',
    impatto: { LAB_AUDIO: -5, LAB_LUCI: -2, LAB_COMEDY: 4, LAB_PRES: 3 },
  },
  {
    id: 'Q51',
    testo: 'Quanto ti piace l\'idea di montare uno spettacolo lavorando agli effetti video?',
    labelLeft: 'Poco',
    labelRight: 'Molto',
    impatto: { LAB_VIDEO: 5, LAB_LUCI: 2, LAB_AUDIO: 1, LAB_NAO: -1, LAB_COMEDY: -2 },
  },
  {
    id: 'Q52',
    testo: 'Preferisci esibirti con un gruppo coordinato o brillare da solo davanti a tutti?',
    labelLeft: 'Con un gruppo coordinato',
    labelRight: 'Da solo davanti a tutti',
    impatto: { LAB_NAO: -4, LAB_DRONI: -2, LAB_PRES: 4, LAB_COMEDY: 2, LAB_AUDIO: -1 },
  },
  {
    id: 'Q53',
    testo: 'L\'idea di stare a una consolle piena di pulsanti e cursori da gestire ti...',
    labelLeft: 'Non attira per niente',
    labelRight: 'Affascina molto',
    impatto: { LAB_AUDIO: 4, LAB_LUCI: 4, LAB_VIDEO: 2, LAB_PRES: -3, LAB_COMEDY: -3 },
  },
  {
    id: 'Q54',
    testo: 'Quanto ti piacerebbe inventare gag e momenti comici per uno spettacolo?',
    labelLeft: 'Non saprei da dove iniziare',
    labelRight: 'Ho mille idee',
    impatto: { LAB_COMEDY: 5, LAB_PRES: 1, LAB_VIDEO: 1, LAB_AUDIO: -2, LAB_DRONI: -2 },
  },
  {
    id: 'Q55',
    testo: 'Quando pensi a tecnologia e spettacolo insieme, ti vedi più con droni in volo o con robot che danzano?',
    labelLeft: 'Con i droni in volo',
    labelRight: 'Con i robot che danzano',
    impatto: { LAB_DRONI: -4, LAB_NAO: 4 },
  },
];
